bunch of fixes

diff --git a/runs/init b/runs/init
--- a/runs/init
+++ b/runs/init
@@ -9,28 +9,30 @@ NOC="\033[0m"
 
 DOTFILES_DIR="$HOME/.dotfiles"
 ENV_DIR="$DOTFILES_DIR/env"
-LISTS_DIR="$DOTFILES_DIR/runs/lists"
+RUNS_DIR="$DOTFILES_DIR/runs"
+LISTS_DIR="$RUNS_DIR/lists"
 
-declare DISTRO INSTALL_CMD UPDATE_CMD AI DEVICE_NAME GPU_TYPE GIT_USER GIT_MAIL
+declare DISTRO INSTALL_CMD UPDATE_CMD AI DEVICE_NAME GPU_TYPE GIT_USER GIT_MAIL \
+	PASSWORDLESS
 
 log() {
 	local level=$1 msg=$2 date
 	date=$(date +"%F %T")
 	case "${level,,}" in
 		err | error)
-			printf "[%s] [$RED\0ERROR$NOC\0] %s\n" "$date" "$msg" >&2
+			printf "[%s] [$RED\0ERROR$NOC\0] %b\n" "$date" "$msg" >&2
 			exit 1
 			;;
 		war | warning)
-			printf "[%s] [$YEL\0WARN $NOC\0] %s\n" "$date" "$msg"
+			printf "[%s] [$YEL\0WARN $NOC\0] %b\n" "$date" "$msg"
 			return 0
 			;;
 		inf | info)
-			printf "[%s] [$BLU\0INFO $NOC\0] %s\n" "$date" "$msg"
+			printf "[%s] [$BLU\0INFO $NOC\0] %b\n" "$date" "$msg"
 			return 0
 			;;
 		suc | success)
-			printf "[%s] [$GRE\0YATA!$NOC\0] %s\n" "$date" "$msg"
+			printf "[%s] [$GRE\0YATA!$NOC\0] %b\n" "$date" "$msg"
 			return 0
 			;;
 	esac
@@ -42,14 +44,6 @@ get_var() {
 		read -rp "Enter $MAG\0hostname$NOC\0: " DEVICE_NAME
 	done
 
-	until [[ $GPU_TYPE == 'nvidia' || $GPU_TYPE == 'amd' ]]; do
-		read -rp "Enter $MAG\0gpu$NOC\0: [nvidia/amd] " GPU_TYPE
-
-		if [[ "$GPU_TYPE" != "nvidia" && "$GPU_TYPE" != "amd" ]]; then
-			log err "$MAG$GPU_TYPE$NOC not supported"
-		fi
-	done
-
 	while [[ -z $GIT_USER ]]; do
 		read -rp "Enter $MAG\0git user.name$NOC\0: " GIT_USER
 	done
@@ -58,9 +52,19 @@ get_var() {
 		read -rp "Enter $MAG\0git user.email$NOC\0: " GIT_MAIL
 	done
 
+	until [[ ${PASSWORDLESS,,} == 'y' || ${PASSWORDLESS,,} == 'n' ]]; do
+		read -rp "Setup passwordless sudo for $MAG$USER$NOC ? [y/n] " PASSWORDLESS
+	done
+
 	until [[ ${AI,,}  == 'y' || ${AI,,} == 'n' ]]; do
 		read -rp "Install $MAG\0local AI models$NOC\0 ? [y/n] " AI
 	done
+
+	while read -r gpu; do
+		[[ ${gpu,,} == *vga* ]] || continue
+		[[ ${gpu,,} == *nvidia* ]] && GPU_TYPE='nvidia' && break
+		[[ ${gpu,,} == *amd* ]] && GPU_TYPE='amd' && break
+	done < <(lspci)
 
 	log suc "Variables have been setup"
 }
@@ -78,9 +82,9 @@ get_distro() {
 		INSTALL_CMD="sudo apt-get install -qy"
 		UPDATE_CMD="sudo apt-get update -qy && sudo apt-get upgrade -qy"
 		;;
-	suse)
-		INSTALL_CMD="sudo zypper in -qn"
-		UPDATE_CMD="sudo zypper dup -qn"
+	opensuse*)
+		INSTALL_CMD="sudo zypper -qn in"
+		UPDATE_CMD="sudo zypper -qn dup"
 		;;
 	# arch)
 	# 	INSTALL_CMD="sudo pacman -Sq --noconfirm --needed"
@@ -94,13 +98,18 @@ get_distro() {
 
 update_pkgs() {
 	log inf "Updating packages"
-	$UPDATE_CMD || log err "Packages update failed"
+	eval "$UPDATE_CMD" || log err "Packages update failed"
 	log suc "Packages have been updated"
+}
+
+install_pkgs() {
+	local pkgs=$*
+	eval "$INSTALL_CMD $pkgs"
 }
 
 set_stow() {
 	log inf "Stowing dotfiles"
-	$INSTALL_CMD stow
+	install_pkgs stow
 	stow -d "$DOTFILES_DIR" -t "$HOME" env
 	log inf "Dotfiles have been stowed"
 
@@ -122,23 +131,19 @@ set_sudoer() {
 		return 0
 	fi
 
-	local answer
-	until [[ ${answer,,} == 'y' || ${answer,,} == 'n' ]]; do
-		read -rp "Setup passwordless sudo for $MAG$USER ? [y/n] " answer
-		if [[ ${answer,,} == 'y' ]]; then
-			printf '%%wheel\tALL=(ALL)\tNOPASSWD: ALL\n' \
-				| sudo tee "$wheel_file" &>/dev/null
-			sudo chmod 0440 "$wheel_file"
-			log suc "Passwordless sudo has been setup for $MAG$USER$NOC"
-		fi
-	done
+	if [[ ${PASSWORDLESS,,} == 'y' ]]; then
+		printf '%%wheel\tALL=(ALL)\tNOPASSWD: ALL\n' \
+			| sudo tee "$wheel_file" &>/dev/null
+		sudo chmod 0440 "$wheel_file"
+		log suc "Passwordless sudo has been setup for $MAG$USER$NOC"
+	fi
 
 	log suc "$MAG$USER$NOC has been added to wheel group"
 }
 
 set_mounts() {
 	log inf "Mounting NFS shares"
-	$INSTALL_CMD nfs-utils || $INSTALL_CMD nfs-common
+	install_pkgs nfs-utils || install_pkgs nfs-common
 	local share_opts="nfs rw,defaults,soft,_netdev,noatime,nodiratime 0 0"
 	while read -r l; do
 		IFS=\; read -r ip dataset mount <<< "$l"
@@ -179,7 +184,7 @@ set_ssh() {
 
 set_git() {
 	log inf "Setting up git"
-	$INSTALL_CMD git
+	install_pkgs git
 	git config --global user.name "$GIT_USER"
 	git config --global user.email "$GIT_MAIL"
 
@@ -208,7 +213,7 @@ set_repos() {
 		[[ -d $dest_dir ]] || mkdir -p "$dest_dir"
 		[[ -d $dest_dir/${name#*/} ]] && continue
 		git clone --recurse-submodules \
-			"ssh://git@$host/$name.git" "$dest_dir"
+			"https://$host/$name.git" "$dest_dir/${name#*/}"
 	done < "$LISTS_DIR/repos"
 
 	log suc "Repos have been setup"
@@ -239,7 +244,7 @@ get_pkgs() {
 
 	done < "$LISTS_DIR/packages"
 
-	$INSTALL_CMD "${to_install[@]}"
+	install_pkgs "${to_install[*]}"
 	log suc "Packages have been installed"
 }
 
@@ -247,22 +252,23 @@ install_ai() {
 	[[ ${AI,,} == 'y' ]] || return 0
 
 	log inf "Installing AI local models"
-	$INSTALL_CMD ollama
+	install_pkgs ollama
 
 	local ollama_modelfiles="$ENV_DIR/.config/ollama/modelfiles"
-	mkdir -p "$ollama_modelfiles"
 	while read -r model; do
+		ollama serve &>/dev/null
 		ollama pull "$model"
 		local modelfile="$ollama_modelfiles/Modelfile_$model"
-		if [[ ! -f $modelfile ]]; then
-			printf 'FROM %s\nPARAMETER num_ctx 16384' "$model" > "$modelfile"
-		fi
-
+		[[ -f $modelfile ]] || printf \
+			'FROM %s\nPARAMETER num_ctx 16384' "$model" \
+			> "$modelfile"
 		ollama create "$model"-16k -f "$modelfile"
 		ollama rm "$model"
 	done < "$LISTS_DIR/ai_models"
 
-	curl -fsSL https://opencode.ai/install | bash
+	if command -v opencode &>/dev/null; then
+		curl -fsSL https://opencode.ai/install | bash
+	fi
 	log suc "AI local models have been install"
 }
 
@@ -280,8 +286,8 @@ install_font() {
 	fi
 
 	log inf "Installing Iosevka font"
-	"$DOTFILES_DIR/runs/build_iosevka.sh" "$INSTALL_CMD" "$ENV_DIR" \
-		"$font_dir" || (log err "Iosevka build failed" && exit 1)
+	eval "$RUNS_DIR/build_iosevka.sh $INSTALL_CMD $ENV_DIR $font_dir" \
+		|| (log err "Iosevka build failed" && exit 1)
 	fc-cache -fv
 	log suc "Iosevka font has been installed"
 }
@@ -300,14 +306,16 @@ install_others() {
 	fi
 
 	# Keyd
-	if ! command -v keyd &>/dev/null; then
-		local src_dir="$HOME/src"
-		[[ -d $src_dir ]] || mkdir -p "$src_dir"
-		git clone "https://github.com/rvaiya/keyd.git" "$src_dir"
-		cd "$src_dir/keyd" || log err "Could not cd into $src_dir/keyd"
+	if [[ $DISTRO == 'fedora' ]] && ! command -v keyd &>/dev/null; then
+		local keyd_dir="$HOME/src/keyd"
+		mkdir -p "$keyd_dir"
+		git clone "https://github.com/rvaiya/keyd.git" "$keyd_dir"
+		cd "$keyd_dir" || log err "Could not cd into $keyd_dir"
 		make && sudo make install
+		[[ -d /etc/keyd ]] || sudo mkdir -p /etc/keyd
 		sudo ln -fs "$ENV_DIR/.config/keyd/default.conf" \
-			/etc/keyd/
+			/etc/keyd/default.conf
+
 		sudo systemctl enable --now keyd
 	fi
 
@@ -315,7 +323,14 @@ install_others() {
 }
 
 post_fedora() {
-	$INSTALL_CMD \
+	local to_install=(
+		--exclude=gstreamer1-plugins-bad-free-devel
+		gstreamer1-plugins-{bad-\*,good-\*,base}
+		gstreamer1-plugin-openh264 gstreamer1-libav lame\* ffmpeg-libs
+		libva libva-utils openh264 mozilla-openh264
+	)
+
+	install_pkgs \
 		https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-"$(rpm -E %fedora)".noarch.rpm \
 		https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-"$(rpm -E %fedora)".noarch.rpm
 
@@ -323,65 +338,69 @@ post_fedora() {
 	sudo dnf group install -qy multimedia sound-and-video
 	sudo dnf check-update
 	sudo dnf swap -qy ffmpeg-free ffmpeg --allowerasing
-	$INSTALL_CMD --exclude=gstreamer1-plugins-bad-free-devel \
-		gstreamer1-plugins-{bad-\*,good-\*,base} \
-		gstreamer1-plugin-openh264 gstreamer1-libav lame\* \
-		ffmpeg-libs libva libva-utils openh264 mozilla-openh264
 
 	case $GPU_TYPE in
 		nvidia)
-			$INSTALL_CMD libva-nvidia-driver kernel-devel \
-				kernel-headers gcc make dkms acpid \
-				libglvnd-glx libglvnd-opengl libglvnd-devel \
-				pkgconfig akmod-nvidia xorg-x11-drv-nvidia-cuda
+			to_install+=( libva-nvidia-driver kernel-devel
+				kernel-headers gcc make dkms acpid libglvnd-glx
+				libglvnd-opengl libglvnd-devel pkgconfig
+				akmod-nvidia xorg-x11-drv-nvidia-cuda
+			)
 			;;
 		amd)
-			$INSTALL_CMD mesa-dri-drivers mesa-vulkan-drivers \
+			to_install+=( mesa-dri-drivers mesa-vulkan-drivers
 				vulkan-loader mesa-libGLU
+			)
 			;;
 	esac
 
+	install_pkgs "${to_install[*]}"
 	sudo dnf config-manager --set-enabled fedora-cisco-openh264
 }
 
 post_debian() {
-	$INSTALL_CMD libavcodec-extra
+	local to_install=(libavcodec-extra)
 	case $GPU_TYPE in
 		nvidia)
-			$INSTALL_CMD nvidia-kernel-dkms nvidia-driver
+			to_install+=(nvidia-kernel-dkms nvidia-driver)
 			;;
 		amd)
 			deb http://deb.debian.org/debian bookworm main contrib non-free-firmware
 			sudo apt-get update -q
-			$INSTALL_CMD firmware-amd-graphics libgl1-mesa-dri \
-				libglx-mesa0 mesa-vulkan-drivers \
+			to_install+=(firmware-amd-graphics libgl1-mesa-dri
+				libglx-mesa0 mesa-vulkan-drivers
 				xserver-xorg-video-all
+			)
 			;;
 	esac
+
+	install_pkgs "${to_install[*]}"
 
 }
 
 post_suse() {
 	printf "export ZYPP_MEDIANETWORK=1\n" >> "$ENV_DIR/.zsh_profile"
-	$INSTALL_CMD opi pipewire pipewire-pulseaudio
+	install_pkgs opi
 	opi -n codecs
-	systemctl --user enable --now pipewire.{service,socket} \
-		pipewire-pulse.{service,socket} wireplumber.service
-
+	to_install=(pipewire pipewire-pulseaudio)
 	case $GPU_TYPE in
 		nvidia)
-			$INSTALL_CMD openSUSE-repos-Tumbleweed-NVIDIA
+			install_pkgs openSUSE-repos-Tumbleweed-NVIDIA
 			sudo zypper install-new-recommends
 			;;
 		amd)
-			$INSTALL_CMD kernel-firmware-amdgpu xf86-video-amdgpu
+			to_install+=(kernel-firmware-amdgpu xf86-video-amdgpu)
 			;;
 	esac
+
+	install_pkgs "${to_install[*]}"
+	systemctl --user enable --now pipewire.{service,socket} \
+		pipewire-pulse.{service,socket} wireplumber.service
 }
 
 post_setup() {
 	log inf "Starting post installation"
-	$UPDATE_CMD
+	update_pkgs
 
 	case $DISTRO in
 		fedora) post_fedora ;;
@@ -393,15 +412,15 @@ post_setup() {
 		local tmp && tmp=$(mktemp)
 		trap 'rm -f "$tmp"' EXIT
 		local sway_dir="/usr/local/share/wayland-sessions"
-		local sway="$sway_dir/sway.desktop"
+		local sway_file="$sway_dir/sway.desktop"
 		[[ -d $sway_dir ]] || sudo mkdir -p $sway_dir
-		[[ -f $sway ]] || sudo touch "$sway"
+		[[ -f $sway_file ]] || sudo touch "$sway_file"
 		while IFS= read -r l; do
 			[[ $l == Exec=* ]] && l="Exec=sway --unsupported-gpu"
 			echo "$l" >> "$tmp"
-		done < "$sway"
+		done < "$sway_file"
 
-		sudo mv "$tmp" "$sway" && sudo chmod 644 "$sway"
+		sudo mv "$tmp" "$sway_file" && sudo chmod 644 "$sway_file"
 	fi
 
 	sudo fwupdmgr get-devices
