learning bash

diff --git a/runs/init b/runs/init
--- a/runs/init
+++ b/runs/init
@@ -1,15 +1,9 @@
 #!/usr/bin/env bash
 
 dots_dir="$HOME/.dotfiles"
-scripts=$(ls "$dots_dir"/runs/*.sh)
 
-if [[ -z "$scripts" ]]; then
-    echo "[INFO] no scripts found."
-    exit 0
-fi
+while read -r script; do
+    "$script" || echo "[WARN] $script failed."
+done < <(find "$dots_dir/runs" -name "*.sh")
 
-for script in $scripts; do
-    $script || echo "[ERR ] $script failed."
-done
-
-stow -R "$dots_dir"/env
+stow -d "$HOME/.dotfiles" -t "$HOME" env
